# Generated by Django 5.0.1 on 2024-01-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cliente", "0002_comentario"),
    ]

    operations = [
        migrations.CreateModel(
            name="hola",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("m", models.TextField()),
            ],
        ),
    ]
